name:                aoc2019
version:             0.1.0.0
github:              githubuser/aoc2019
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/githubuser/aoc2019#readme>

dependencies:
- base >= 4.11 && < 10
- relude

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - vector
    - text
  default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - OverloadedLists
  - LambdaCase
  - GADTSyntax
  - RankNTypes
  - ScopedTypeVariables
  - DeriveGeneric
  - TupleSections
  - BangPatterns
  - MultiParamTypeClasses
  - FlexibleInstances
  - FlexibleContexts
  - MultiWayIf
  - TypeFamilies
  - TypeOperators
  - FunctionalDependencies
  - DisambiguateRecordFields
  - MonadComprehensions
  - BinaryLiterals
  - RecursiveDo
  - ParallelListComp
  - PartialTypeSignatures
  - RecordWildCards
  - PatternSynonyms
  - EmptyCase
  - InstanceSigs
  - KindSignatures
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - ConstraintKinds
  - ExplicitNamespaces

executables:
  aoc2019-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - aoc2019
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  aoc2019-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - aoc2019
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
