name: aoc2019
version: 0.1.0.0
github: z0isch/aoc2019
license: BSD3
author: AJ Ruf
copyright: 2019 AJ Ruf

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README on Github at <https://github.com/githubuser/aoc2019#readme>

dependencies:
  - base >= 4.11 && < 10
  - relude

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - LambdaCase
  - GADTSyntax
  - RankNTypes
  - ScopedTypeVariables
  - DeriveGeneric
  - TupleSections
  - BangPatterns
  - MultiParamTypeClasses
  - FlexibleInstances
  - FlexibleContexts
  - MultiWayIf
  - TypeFamilies
  - TypeOperators
  - FunctionalDependencies
  - DisambiguateRecordFields
  - MonadComprehensions
  - BinaryLiterals
  - RecursiveDo
  - ParallelListComp
  - PartialTypeSignatures
  - RecordWildCards
  - PatternSynonyms
  - EmptyCase
  - InstanceSigs
  - KindSignatures
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - ConstraintKinds
  - ExplicitNamespaces
  - NamedFieldPuns
  - DerivingStrategies
  - GeneralizedNewtypeDeriving

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - vector
    - text
    - megaparsec
    - containers
    - unordered-containers
    - intervals
    - linear
    - monad-loops
    - JuicyPixels
    - lens

executables:
  aoc2019-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - aoc2019
      - optparse-simple

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  aoc2019-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - aoc2019
      - hspec

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
